name: Build using Docker

on:
  push:
    branches: [ "dev", "test" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: [self-hosted, vanity]
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Build using Docker
      run: /bin/bash release-builder.sh
    - uses: actions/upload-artifact@v3
      with:
        name: build-${{ env.GITHUB_SHA }}
        path: |
          release-build/xahaud
          release-build/release.info
    - name: Unit tests
      run: /bin/bash docker-unit-tests.sh
