name: Build using Docker

on:
  push:
    branches: [ "dev", "test" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: [self-hosted, vanity]
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Build using Docker
      run: /bin/bash release-builder.sh
    - uses: actions/upload-artifact@v3
      with:
        name: build-$GITHUB_SHA
        path: release-build/xahaud
    - uses: actions/upload-artifact@v3
      with:
        name: releaseinfo-$GITHUB_SHA
        path: release-build/release.info
    - name: Unit tests
      run: /bin/bash release-build/xahaud -u
